export const HOTELS = [
  {
    "id": "MQ001",
    "name": "Royal Palm Beachcomber Luxury",
    "region": "Grand Baie",
    "overall": 9.2,
    "location": 9.4,
    "amenity": 9.1,
    "brand": 9,
    "value": 7.2,
    "reviews": 1340,
    "avgRating": 4.8,
    "price": 1450,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "butler_service": true,
      "fine_dining": true,
      "pool": true,
      "gym": true,
      "concierge": true,
      "private_pool": true
    },
    "link": "https://expedia.com/affiliate/LLPswc1"
  },
  {
    "id": "MQ002",
    "name": "Four Seasons Resort Mauritius at Anahita",
    "region": "Beau Champ",
    "overall": 9.1,
    "location": 9.3,
    "amenity": 9.4,
    "brand": 9.5,
    "value": 7,
    "reviews": 1120,
    "avgRating": 4.9,
    "price": 1650,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "butler_service": true,
      "fine_dining": true,
      "pool": true,
      "golf": true,
      "gym": true,
      "concierge": true,
      "private_pool": true,
      "overwater_villa": true,
      "kids_club": true
    },
    "link": "https://expedia.com/affiliate/s7PgDXw"
  },
  {
    "id": "MQ003",
    "name": "One&Only Le Saint Géran",
    "region": "Belle Mare",
    "overall": 9,
    "location": 9.2,
    "amenity": 9,
    "brand": 9.3,
    "value": 6.8,
    "reviews": 980,
    "avgRating": 4.8,
    "price": 1380,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "butler_service": true,
      "fine_dining": true,
      "pool": true,
      "gym": true,
      "concierge": true,
      "private_pool": true,
      "wellness_programmes": true
    },
    "link": "https://expedia.com/affiliate/jJhAhIn"
  },
  {
    "id": "MQ004",
    "name": "Constance Le Chaland Iko Mauritius",
    "region": "Blue Bay",
    "overall": 8.8,
    "location": 9,
    "amenity": 8.8,
    "brand": 8.6,
    "value": 7.4,
    "reviews": 1560,
    "avgRating": 4.7,
    "price": 820,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "golf": true,
      "kids_club": true,
      "gym": true,
      "water_sports": true,
      "wellness_programmes": true
    },
    "link": "https://expedia.com/affiliate/a1VWvT2"
  },
  {
    "id": "MQ006",
    "name": "Lux* Grand Gaube Resort & Villas",
    "region": "Grand Gaube",
    "overall": 8.7,
    "location": 8.8,
    "amenity": 8.6,
    "brand": 8.5,
    "value": 7.8,
    "reviews": 1430,
    "avgRating": 4.7,
    "price": 680,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "gym": true,
      "water_sports": true,
      "wellness_programmes": true
    },
    "link": "https://expedia.com/affiliate/usEpyj6"
  },
  {
    "id": "MQ007",
    "name": "Constance Prince Maurice",
    "region": "Poste de Flacq",
    "overall": 9,
    "location": 9.2,
    "amenity": 9.1,
    "brand": 9,
    "value": 7,
    "reviews": 890,
    "avgRating": 4.8,
    "price": 1250,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "butler_service": true,
      "fine_dining": true,
      "pool": true,
      "overwater_villa": true,
      "wellness_programmes": true
    },
    "link": "https://expedia.com/affiliate/WmRuuHu"
  },
  {
    "id": "MQ008",
    "name": "Paradise Cove Boutique Hotel - Adults Only",
    "region": "Cap Malheureux",
    "overall": 9,
    "location": 9.1,
    "amenity": 8.9,
    "brand": 8.5,
    "value": 7.8,
    "reviews": 194,
    "avgRating": 4.7,
    "price": 890,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "adults_only": true,
      "wellness_programmes": true
    },
    "link": "https://expedia.com/affiliate/KYUg6DO"
  },
  {
    "id": "MQ009",
    "name": "Lagoon Attitude - Adults Only",
    "region": "Cap Malheureux",
    "overall": 8.7,
    "location": 8.8,
    "amenity": 8.6,
    "brand": 8,
    "value": 8.2,
    "reviews": 81,
    "avgRating": 4.6,
    "price": 520,
    "stars": 4,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "adults_only": true
    },
    "link": "https://expedia.com/affiliate/4toq7Ie"
  },
  {
    "id": "MQ010",
    "name": "Mythic Suites & Villas by MJ Holidays",
    "region": "Grand Gaube",
    "overall": 8.4,
    "location": 8.5,
    "amenity": 8.2,
    "brand": 7.8,
    "value": 8.3,
    "reviews": 8,
    "avgRating": 4.4,
    "price": 500,
    "stars": 4,
    "amenities": {
      "pool": true,
      "fine_dining": true,
      "high_speed_wifi": true
    },
    "link": "https://expedia.com/affiliate/c9Mfa5v"
  },
  {
    "id": "MQ011",
    "name": "Sea Diamond Boutique Hotel & Spa by Sea Resorts",
    "region": "Cap Malheureux",
    "overall": 8.5,
    "location": 8.7,
    "amenity": 8.4,
    "brand": 8,
    "value": 8,
    "reviews": 0,
    "avgRating": 4.5,
    "price": 680,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "wellness_programmes": true
    },
    "link": "https://expedia.com/affiliate/FA2X6xD"
  },
  {
    "id": "MQ012",
    "name": "Villa Alizée",
    "region": "Port Louis",
    "overall": 8.3,
    "location": 8.2,
    "amenity": 8.1,
    "brand": 7.5,
    "value": 8.4,
    "reviews": 12,
    "avgRating": 4.7,
    "price": 415,
    "stars": 4,
    "amenities": {
      "fine_dining": true,
      "pool": true,
      "high_speed_wifi": true
    },
    "link": "https://expedia.com/affiliate/FyoIgaK"
  },
  {
    "id": "MQ013",
    "name": "Heritage Awali Golf & Spa Resort",
    "region": "Bel Ombre",
    "overall": 8.4,
    "location": 8.7,
    "amenity": 8.3,
    "brand": 8.1,
    "value": 7.8,
    "reviews": 890,
    "avgRating": 4.5,
    "price": 640,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "golf": true,
      "wellness_programmes": true
    },
    "link": "https://expedia.com/affiliate/TzDUcJc"
  },
  {
    "id": "MQ014",
    "name": "LUX* Belle Mare",
    "region": "Belle Mare",
    "overall": 8.6,
    "location": 8.8,
    "amenity": 8.5,
    "brand": 8.5,
    "value": 7.7,
    "reviews": 1050,
    "avgRating": 4.6,
    "price": 730,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "gym": true,
      "wellness_programmes": true,
      "yoga": true
    },
    "link": "https://expedia.com/affiliate/FfYvZuT"
  },
  {
    "id": "MQ015",
    "name": "Oberoi Beach Resort Mauritius",
    "region": "Grand Baie",
    "overall": 8.8,
    "location": 9,
    "amenity": 8.9,
    "brand": 8.9,
    "value": 7.3,
    "reviews": 760,
    "avgRating": 4.8,
    "price": 1050,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "butler_service": true,
      "fine_dining": true,
      "pool": true,
      "wellness_programmes": true,
      "yoga": true,
      "meditation": true
    },
    "link": "https://expedia.com/affiliate/o4m2Ako"
  },
  {
    "id": "MQ016",
    "name": "Zilwa Attitude",
    "region": "Cap Malheureux",
    "overall": 8.2,
    "location": 8.5,
    "amenity": 8,
    "brand": 7.8,
    "value": 8.4,
    "reviews": 1320,
    "avgRating": 4.4,
    "price": 340,
    "stars": 4,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "pool": true,
      "water_sports": true,
      "kids_club": true,
      "high_speed_wifi": true
    },
    "link": "https://expedia.com/affiliate/yLn0geY"
  },
  {
    "id": "MQ021",
    "name": "The Westin Turtle Bay Resort & Spa, Mauritius",
    "region": "Balaclava",
    "overall": 8.6,
    "location": 8.9,
    "amenity": 8.7,
    "brand": 8.8,
    "value": 7.6,
    "reviews": 840,
    "avgRating": 4.6,
    "price": 650,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "gym": true,
      "wellness_programmes": true,
      "yoga": true,
      "concierge": true
    },
    "link": "https://expedia.com/affiliate/PJytcSS"
  },
  {
    "id": "MQ022",
    "name": "Constance Belle Mare Plage",
    "region": "Belle Mare",
    "overall": 8.9,
    "location": 9.2,
    "amenity": 8.8,
    "brand": 8.8,
    "value": 7.3,
    "reviews": 950,
    "avgRating": 4.7,
    "price": 920,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "golf": true,
      "kids_club": true,
      "gym": true,
      "water_sports": true,
      "wellness_programmes": true,
      "concierge": true
    },
    "link": "https://expedia.com/affiliate/joE5IeP"
  },
  {
    "id": "MQ023",
    "name": "The Ravenala Attitude",
    "region": "Balaclava",
    "overall": 8.1,
    "location": 8.3,
    "amenity": 8,
    "brand": 7.7,
    "value": 8.3,
    "reviews": 1080,
    "avgRating": 4.4,
    "price": 290,
    "stars": 4,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "kids_club": true,
      "water_sports": true,
      "high_speed_wifi": true
    },
    "link": "https://expedia.com/affiliate/k1alVSX"
  },
  {
    "id": "MQ024",
    "name": "20 Degres Sud",
    "region": "Grand Baie",
    "overall": 8.2,
    "location": 8.4,
    "amenity": 7.9,
    "brand": 7.4,
    "value": 8.2,
    "reviews": 320,
    "avgRating": 4.5,
    "price": 280,
    "stars": 4,
    "amenities": {
      "pool": true,
      "fine_dining": true,
      "high_speed_wifi": true,
      "dedicated_workspace": true,
      "business_centre": true
    },
    "link": "https://expedia.com/affiliate/2VMyMj0"
  },
  {
    "id": "MQ025",
    "name": "Shanti Maurice Resort & Spa",
    "region": "Chemin Grenier",
    "overall": 8.8,
    "location": 8.7,
    "amenity": 9,
    "brand": 8.3,
    "value": 7.4,
    "reviews": 580,
    "avgRating": 4.7,
    "price": 820,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "yoga": true,
      "wellness_programmes": true,
      "meditation": true,
      "healthy_dining": true,
      "gym": true,
      "naturopath": true
    },
    "link": "https://expedia.com/affiliate/AMUhp0j"
  },
  {
    "id": "MQ026",
    "name": "SALT of Palmar",
    "region": "Palmar",
    "overall": 8.3,
    "location": 8.5,
    "amenity": 8.1,
    "brand": 7.5,
    "value": 8.2,
    "reviews": 270,
    "avgRating": 4.5,
    "price": 350,
    "stars": 4,
    "amenities": {
      "pool": true,
      "fine_dining": true,
      "high_speed_wifi": true,
      "dedicated_workspace": true,
      "private_beach": true
    },
    "link": "https://expedia.com/affiliate/rHzTaO0"
  },
  {
    "id": "MQ027",
    "name": "Holiday Inn Mauritius Mon Tresor",
    "region": "Plaine Magnien",
    "overall": 7.8,
    "location": 7.5,
    "amenity": 7.9,
    "brand": 8,
    "value": 8.6,
    "reviews": 620,
    "avgRating": 4.2,
    "price": 190,
    "stars": 4,
    "amenities": {
      "pool": true,
      "fine_dining": true,
      "kids_club": true,
      "high_speed_wifi": true,
      "business_centre": true,
      "gym": true
    },
    "link": "https://expedia.com/affiliate/KrkFlUB"
  },
  {
    "id": "MQ028",
    "name": "Sands Suites Resort & Spa",
    "region": "Flic En Flac",
    "overall": 7.9,
    "location": 8.2,
    "amenity": 7.8,
    "brand": 7.3,
    "value": 8.5,
    "reviews": 760,
    "avgRating": 4.3,
    "price": 210,
    "stars": 4,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "gym": true
    },
    "link": "https://expedia.com/affiliate/jJkyMlG"
  },
  {
    "id": "MQ029",
    "name": "Le Meridien Ile Maurice",
    "region": "Pointe Aux Piments",
    "overall": 8.5,
    "location": 8.7,
    "amenity": 8.6,
    "brand": 8.7,
    "value": 7.7,
    "reviews": 890,
    "avgRating": 4.5,
    "price": 560,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "kids_club": true,
      "gym": true,
      "water_sports": true,
      "high_speed_wifi": true,
      "concierge": true
    },
    "link": "https://expedia.com/affiliate/8C3UdBg"
  },
  {
    "id": "MQ030",
    "name": "Jacaranda Luxury Villas by Maritim",
    "region": "Balaclava",
    "overall": 8.5,
    "location": 8.6,
    "amenity": 8.4,
    "brand": 8.2,
    "value": 7.7,
    "reviews": 380,
    "avgRating": 4.5,
    "price": 620,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "butler_service": true,
      "fine_dining": true,
      "pool": true,
      "private_pool": true,
      "concierge": true
    },
    "link": "https://expedia.com/affiliate/uzq9Zlu"
  },
  {
    "id": "MQ031",
    "name": "Tamassa Resort",
    "region": "Bel Ombre",
    "overall": 7.9,
    "location": 8.1,
    "amenity": 8,
    "brand": 8.1,
    "value": 8.7,
    "reviews": 1020,
    "avgRating": 4.3,
    "price": 280,
    "stars": 4,
    "amenities": {
      "pool": true,
      "private_beach": true,
      "fine_dining": true,
      "all_inclusive": true,
      "water_sports": true,
      "kids_club": true,
      "gym": true,
      "free_water_sports": true
    },
    "link": "https://expedia.com/affiliate/oSrAbiY"
  },
  {
    "id": "MQ032",
    "name": "Bubble Lodge Ile Aux Cerfs",
    "region": "Trou d'Eau Douce",
    "overall": 8.4,
    "location": 9.1,
    "amenity": 7.8,
    "brand": 7.3,
    "value": 7.5,
    "reviews": 140,
    "avgRating": 4.6,
    "price": 750,
    "stars": 4,
    "amenities": {
      "pool": true,
      "fine_dining": true,
      "private_beach": true
    },
    "link": "https://expedia.com/affiliate/nOTJrFM"
  },
  {
    "id": "MQ033",
    "name": "Hilton Mauritius Resort & Spa",
    "region": "Flic En Flac",
    "overall": 8.7,
    "location": 8.9,
    "amenity": 8.8,
    "brand": 8.9,
    "value": 7.6,
    "reviews": 1180,
    "avgRating": 4.6,
    "price": 530,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "fine_dining": true,
      "pool": true,
      "kids_club": true,
      "gym": true,
      "concierge": true,
      "high_speed_wifi": true,
      "wellness_programmes": true
    },
    "link": "https://expedia.com/affiliate/lb9Yl8f"
  },
  {
    "id": "MQ034",
    "name": "Anahita Golf & Spa Resort",
    "region": "Grand River South East",
    "overall": 8.7,
    "location": 9,
    "amenity": 8.9,
    "brand": 8.5,
    "value": 7.2,
    "reviews": 700,
    "avgRating": 4.6,
    "price": 780,
    "stars": 5,
    "amenities": {
      "spa": true,
      "private_beach": true,
      "butler_service": true,
      "fine_dining": true,
      "pool": true,
      "golf": true,
      "wellness_programmes": true,
      "concierge": true
    },
    "link": "https://expedia.com/affiliate/6oyzyzA"
  }
];
